added massive countdown script and help file

diff --git a/countdown b/countdown
--- a/countdown
+++ b/countdown
@@ -5,6 +5,9 @@
 # Trap the exit to clean the screen a bit
 function quit
 {
+	if [ "$SCREEN" != "$TTY" ]; then
+		eval "`resize -s $OLD_LINES $OLD_COLUMNS`"
+	fi
 	tput rmcup
 	tput cnorm
 	tput sgr0
@@ -15,104 +18,7 @@ trap quit SIGINT SIGTERM
 # Print long usage and exit.
 function long_usage
 {
-	cat <<EOF
-NAME
-	\`countdown' - A countdown timer.
-
-SYNOPSIS
-	countdown {-h, -H} [{-o, -t} time] {-n name}
-
-DESCRIPTION
-	Countdown will display a timer that will count down to zero. The time
-	may be set via the switches -o and -t, and their argument the \`time'
-	string, in the format discussed below. The program uses 24-hour time,
-	thus arguments can be from 0 through 23 for hours, and 0 - 60 for minutes
-	and seconds. The smallest amount of time settable is one second, and
-	other parameters will cause the usage message to be printed and exit.
-
-OPTION SYNOPSIS
-	The timer options are as follows:
-
-	-h
-		Prints the short help.
-
-	-H
-		Prints this long help.
-
-	-o <time>
-		For a timer that is an offset from now.
-		\`countdown -o "1:2:3"' sets a timer for 1 hour,
-		2 minutes, and 3 seconds.
-
-	-t <time>
-		For a timer until a certain time.
-		\`countdown -o "9:30"', when issued at 8:00,
-		sets a timer for 1 hour and 30 minutes;
-		the exact time until 9:30.
-
-	-n <name>
-		For a timer with name \`name' that follows the option.
-		An example would be \`countdown ... -n "Go to bed"'.
-		Using this option will give the timer a name during the countdown,
-		as well as printing that the timer finished by name: both in the
-		terminal and via an Xfce otification (if you are using Xfce,
-		otherwise nothing will happen in your desktop).
-
-TIME STRING FORMAT
-	The format of the \`time' string is a three-field string delimited with
-	either a colon \`:' or space \` '. Each of the three fields corresponds
-	to hours, minutes, and seconds, respectively, and cannot exceed the
-	limit for the given option.
-
-	The field maximum values for each time option is as follows:
-
-	-t
-		-h
-			0 - 23
-		-m
-			0 - 59
-		-s
-			0 - 59
-
-	-o
-		-h
-			0 - 99
-		-m
-			0 - 59
-		-s
-			0 - 59
-
-	Example \`time' strings are:
-
-	-t
-		"12:44:56"
-		"21 43 07"
-		"00:03:43"
-		"08 23 00"
-
-	-o
-		"12:33:56"
-		"21 49 07"
-		"01:03:43"
-		"98 23 10"
-
-NAME STRING
-	The \`name' string can be any string, so long as it is less than 42
-	characters long.
-
-EXAMPLES
-	countdown -t "12:44:56"
-	countdown -t "08 23 00"
-
-	countdown -t "21 43 07" -n "Go to bed"
-	countdown -t "00:03:43" -n "Wake up"
-
-	countdown -o "21 49 07"
-	countdown -o "98 23 10"
-
-	countdown -o "12:33:56" -n "Day to night"
-	countdown -o "01:03:43" -n "A bit more than an hour"
-EOF
+	cat "$HOME/bin/countdown-help.txt" | less
 	quit
 }
 
@@ -120,33 +26,28 @@ EOF
 function usage
 {
 	if [ -n "$1" ]; then
-		cat <<-EOF 1>&2
-		Error: $1
-		Usage: countdown {-h, -H} [{-o, -t} time] {-n name}
-		Use -H for long help.
-		EOF
-	else
-		cat <<-EOF 1>&2
-		Usage: countdown {-h, -H} [{-o, -t} time] {-n name}
-		Use -H for long help.
-		EOF
+		echo "Error: $1" 1>&2
 	fi
+
+	cat <<-EOF 1>&2
+	Usage: countdown {-h, -H} {-i} [{-o, -t} time] {-n name}
+	Use -H for long help.
+	EOF
+
 	quit 1
 }
 
 # Visual alert.
 function play_sound
 {
-
-	[ -z "$NAME" ] && MESSAGE="A countdown timer has finished." \
-		|| MESSAGE="The countdown timer '$NAME' has finished."
-
 	if [ $IN_XFCE ]; then
 		notify-send -u low "$MESSAGE"
 	fi
 
-	echo $MESSAGE
-	aplay $SOUND &> /dev/null
+	tput cuf $DEFAULT_OFFSET
+	echo -n $DEFAULT_MESSAGE
+	tput cr
+	aplay $SOUND &> /dev/null &
 }
 
 # Add to a time and possibly 'wrap over' to past midnight or noon.
@@ -184,96 +85,107 @@ function print_info
 	FIN_MINUTES=`add_times $MINUTES $DEST_MINUTES "m"`
 	FIN_SECONDS=`add_times $SECONDS $DEST_SECONDS "s"`
 
-	[ $FIN_SECONDS -lt $DEST_SECONDS ] && let FIN_MINUTES+=1
-	[ $FIN_MINUTES -lt $DEST_MINUTES ] && let FIN_HOURS+=1
+	[ $FIN_SECONDS -lt $DEST_SECONDS ] && let FIN_MINUTES++
+	[ $FIN_MINUTES -lt $DEST_MINUTES ] && let FIN_HOURS++
 
+	tput cud1
+	tput cuf $HEAD_OFFSET
 	printf "Running countdown: Started at: %02d:%02d:%02d.\n" \
 		$HOURS $MINUTES $SECONDS
+	tput cuf $HEAD_OFFSET
 	printf "Total time: %02d:%02d:%02d, Ends at: %02d:%02d:%02d.\n" \
 		$DEST_HOURS $DEST_MINUTES $DEST_SECONDS \
 		$FIN_HOURS $FIN_MINUTES $FIN_SECONDS
+	echo
 
-	[ "$MODE" == "-t" ] && echo "Absolute time mode." || echo "Offset mode"
+	tput dim
+	tput cuf1; echo "$SPACER_STR"
+	tput cuf1; echo -n "|"; tput cuf $[$SPACER_LENGTH-2]; echo "|"
+	tput cuf1; echo -n "|"; tput cuf $[$SPACER_LENGTH-2]; echo "|"
+	tput cuf1; echo -n "|"; tput cuf $[$SPACER_LENGTH-2]; echo "|"
+	tput cuf1; echo "$SPACER_END_STR"
+	tput sgr0
 
-	echo "$SPACER_STR"
-	sleep 1
-	echo -n "|"; sleep 1; tput cuf $SPACER_NUM_OFFSET; echo "|"
-	echo -n "|"; sleep 1; tput cuf $SPACER_NUM_OFFSET; echo "|"
-	echo -n "|"; sleep 1; tput cuf $SPACER_NUM_OFFSET; echo "|"
-	sleep 1
-	echo "$SPACER_STR"
-	sleep 1
 	tput cuu 3
-	sleep 1
 }
 
 # Verifies if a time is in the future or not.
 function verify_time
 {
 	# The times as one big number.
-	TOTAL="`echo -n \"$HOURS$MINUTES$SECONDS\" | \
+	TMP="`echo -n \"$HOURS$MINUTES$SECONDS\" | \
 		sed 's/^0\+//g'`"
-	DEST_TOTAL="`echo \"$DEST_HOURS$DEST_MINUTES$DEST_SECONDS\" | \
+	[ -z "$TMP" ] && TOTAL="0" || TOTAL="$TMP"
+
+	TMP="`echo \"$DEST_HOURS$DEST_MINUTES$DEST_SECONDS\" | \
 		sed 's/^0\+//g'`"
+	[ -z "$TMP" ] && DEST_TOTAL="0" || DEST_TOTAL="$TMP"
+
 	let DIFFERENCE=$DEST_TOTAL-$TOTAL
 
 	TIME_OK=false
 
-	# Countdown mode: Goes to -1 to display all zeros at the end.
-	[ "$MODE" == "-c" -a "$DEST_TOTAL" != "-1" ] && TIME_OK=true
-
-	# Offset mode.
-	[ "$MODE" == "-o" -a "$DEST_TOTAL" != "0" ] && TIME_OK=true
-
-	# (Absolute) Time mode.
-	[ "$MODE" == "-t" -a "$DIFFERENCE" -gt 0 ] && TIME_OK=true
-}
-
-# 'Subtract' to a time and possibly 'wrap over' to past midnight or noon.
-# Always to be called with 3 arguments: The (clock) time and the (future)
-# time to offset to, as well as a place (h, m, s), to specify hours,
-# minutes, or seconds.
-function time_to_offset
-{
-	CLOCK=$1
-	shift
-	FUTURE=$1
-	shift
-	PLACE=$1
-
-	PLACE_MAX=0
-
-	if [ "$PLACE" == "h" ]; then
-		PLACE_MAX=24
-	elif [ "$PLACE" == "m" -o "$PLACE" == "s" ]; then
-		PLACE_MAX=60
+	if [ "$MODE" == "-c" ]; then
+		# Countdown mode: Goes to -1 to display all zeros at the end.
+		[ "$DEST_TOTAL" -gt 0 ] && TIME_OK=true || TIME_OK=false
+	elif [ "$MODE" == "-o" ]; then
+		# Offset mode.
+		[ "$DEST_TOTAL" -gt 0 ] && TIME_OK=true || TIME_OK=false
+	elif [ "$MODE" == "-t" ]; then
+		# (Absolute) Time mode.
+		[ "$DIFFERENCE" -gt 0 ] && TIME_OK=true || TIME_OK=false
 	else
-		echo "Bad option to add_times" 1>&2
-		quit 2
+		TIME_OK=false
 	fi
 
-	if [ $FUTURE -ge $CLOCK ]; then
-		let NEW_CLOCK=$FUTURE-$CLOCK
-	else
-		let NEW_CLOCK=($PLACE_MAX-$CLOCK)+$FUTURE
-	fi
-
-	echo -n $NEW_CLOCK
 }
 
 # Counts down a second.
 function step_down
 {
-	if [ $DEST_SECONDS -eq 0 ]; then
-		[ $DEST_MINUTES -ne 0 ] && let DEST_SECONDS=59
-		[ $DEST_MINUTES -ne 0 ] && let DEST_MINUTES-=1
-	fi
 	if [ $DEST_MINUTES -eq 0 ]; then
-		[ $DEST_HOURS -ne 0 ] && let DEST_MINUTES=59
-		[ $DEST_HOURS -ne 0 ] && let DEST_HOURS-=1
+		if [ $DEST_HOURS -ne 0 -a $DEST_SECONDS -le 0 ]; then
+			let DEST_HOURS-=1
+			let DEST_MINUTES=59
+			let DEST_SECONDS=60
+			# elif [ $DEST_HOURS -ne 0 -a $DEST_SECONDS -eq 0 ]; then
+			# 	let DEST_MINUTES=59
+		fi
 	fi
 
-	let DEST_SECONDS-=1
+	if [ $DEST_SECONDS -le 0 ]; then
+		[ $DEST_MINUTES -ne 0 ] && let DEST_SECONDS=59
+		[ $DEST_MINUTES -ne 0 ] && let DEST_MINUTES-=1
+	else
+		let DEST_SECONDS-=1
+	fi
+}
+
+# Prints and changes the timer status.
+function manage_time
+{
+	printf "%02dh:%02dm:%02ds" \
+		$DEST_HOURS $DEST_MINUTES $DEST_SECONDS
+	tput cub $TIMER_LENGTH
+
+	verify_time
+	step_down
+	sleep 1
+}
+
+# Prints cool binary background
+function bin_bg
+{
+	tput cup 0 0
+	tput setaf 233
+	COUNT=0
+	MAX_COUNT=$(( (`tput lines`*`tput cols`)-1 ))
+	while [ $COUNT -le $MAX_COUNT ]; do
+		echo -n $[$RANDOM%2]
+		let COUNT++
+	done
+	tput cup 0 0
+	tput sgr0
 }
 
 [ $# -lt 1 ] && usage "Not enough arguments."
@@ -286,10 +198,10 @@ IN_XFCE=false
 MODE=""
 ARGTIME=""
 NAME=""
-while getopts ":o:t:n:hH" OPT; do
+IMMEDIATE=false
+while getopts ":o:t:n:hHi" OPT; do
 	case $OPT in
-		o)
-			MODE="-o"
+		o) MODE="-o"
 			ARGTIME="$OPTARG"
 			;;
 		t)
@@ -304,6 +216,9 @@ while getopts ":o:t:n:hH" OPT; do
 			;;
 		H)
 			long_usage
+			;;
+		i)
+			IMMEDIATE=true
 			;;
 		\?)
 			usage "Invalid option: -$OPTARG."
@@ -320,7 +235,6 @@ ARGTIME_IS_VALID=false
 if echo -n $ARGTIME | grep -q '^[0-9]\{2\}[\: ][0-9]\{2\}[\: ][0-9]\{2\}$'; then
 	HOUR_MAX=0
 	MIN_SEC_MAX=59
-
 	if [ "$MODE" == "-o" ]; then
 		HOUR_MAX=99
 	elif [ "$MODE" == "-t" ]; then
@@ -335,9 +249,6 @@ if echo -n $ARGTIME | grep -q '^[0-9]\{2\}[\: ][0-9]\{2\}[\: ][0-9]\{2\}$'; then
 	DEST_SECONDS="`echo -n $ARGTIME | \
 		sed -e 's/.*\([0-9]\{2\}$\)/\1/' -e 's/^0//'`"
 
-	# Debug
-	echo "DEBUG: $MODE $DEST_HOURS $DEST_MINUTES $DEST_SECONDS"
-
 	[ $DEST_HOURS -le $HOUR_MAX -a $DEST_MINUTES -le $MIN_SEC_MAX -a \
 		$DEST_SECONDS -le $MIN_SEC_MAX ] && ARGTIME_IS_VALID=true
 fi
@@ -347,14 +258,18 @@ if ! $ARGTIME_IS_VALID; then
 fi
 
 # Get the current time and strip leading zeros.
-HOURS="`date +'%H' | sed 's/^0*//'`" MINUTES="`date +'%M' | sed 's/^0*//'`"
-SECONDS="`date +'%S' | sed 's/^0*//'`"
+HOURS="`date +'%H' | sed 's/^0//'`"
+MINUTES="`date +'%M' | sed 's/^0//'`"
+SECONDS="`date +'%S' | sed 's/^0//'`"
 
 # Set variables for the title of the timer to be printed in the terminal.
-[ -z "$NAME" -o ${#NAME} -gt 42 ] && TITLE=" Timer " || TITLE=" $NAME "
+[ -z "$NAME" -o ${#NAME} -lt 5 ] && TITLE=" Timer " || TITLE=" $NAME "
 let TITLE_LEN=${#TITLE}+2
 
-let SPACER_NUM=$TITLE_LEN+15
+let TITLE_PLUS=$TITLE_LEN+5
+WORK_COLS=$(( 42+(42/(4-2)) )) # Why not include 42, 3 times? *Magic* number.
+[ $WORK_COLS -gt $TITLE_PLUS ] && SPACER_NUM=$WORK_COLS || \
+	SPACER_NUM=$TITLE_PLUS
 let SPACER_NUM_OFFSET=$SPACER_NUM-1
 SPACER_CHAR='='
 
@@ -365,25 +280,64 @@ let END_NUM_SPACERS=$(( $SPACER_NUM_HALF+($SPACER_NUM_HALF%2) ))
 FIRST_SPACERS="+`for i in \`seq 1 $FIRST_NUM_SPACERS\`; do printf \"$SPACER_CHAR\"; done`"
 END_SPACERS="`for i in \`seq 1 $END_NUM_SPACERS\`; do printf \"$SPACER_CHAR\"; done`+"
 
+TIMER_FORMAT="00h:00m:00s"
+TIMER_LENGTH=${#TIMER_FORMAT}
+TIMER_OFFSET=$(( ($SPACER_NUM-$TIMER_LENGTH)/2 ))
+
 SPACER_STR="$FIRST_SPACERS$TITLE$END_SPACERS"
+SPACER_END_STR="`echo $SPACER_STR | sed 's/[^+]/'$SPACER_CHAR'/g'`"
 SPACER_LENGTH=${#SPACER_STR}
 
-TIMER_FORMAT="00h:00m:00s"
-TIMER_OFFSET=$(( ($SPACER_NUM-${#TIMER_FORMAT})/2 ))
+# 40 is the length of the header lines.
+HEAD_OFFSET=$(( (($SPACER_NUM-40)/2)+($SPACER_NUM%2) ))
 
 # The sound for the notification.
 SOUND="$HOME/button-09.wav"
 
-# Set times for `-t'.
-if $TIME_OK && [ "$MODE" == "-t" ]; then
-	DEST_HOURS=`time_to_offset $HOURS $DEST_HOURS "h"`
-	DEST_MINUTES=`time_to_offset $MINUTES $DEST_MINUTES "m"`
-	DEST_SECONDS=`time_to_offset $SECONDS $DEST_SECONDS "s"`
+# Message strings
+DEFAULT_MESSAGE="The countdown timer has finished."
+DEFAULT_OFFSET=$(( ($SPACER_NUM-${#DEFAULT_MESSAGE})/2 ))
+[ -z "$NAME" ] && MESSAGE="$DEFAULT_MESSAGE" \
+	|| MESSAGE="The countdown timer '$NAME' has finished."
+
+# The colors for tput.
+COLOR_MIN=17
+COLOR_MAX=231
+COLOR=$COLOR_MIN
+
+# Possibly resize the terminal
+SCREEN="`screen -list | grep -o 'pts-[0-9]\+'`"
+TTY="`tty | sed 's/\/dev\///g'`"
+# [ $SPACER_NUM -gt $SPACER_LENGTH ] && WIDTH=$SPACER_NUM || WIDTH=$SPACER_LENGTH
+WIDTH=$SPACER_LENGTH
+if [ "$SCREEN" != "$TTY" ]; then
+	OLD_LINES="$LINES"
+	OLD_COLUMNS="$COLUMNS"
+	eval "`resize -s 12 $[WIDTH+2]`"
 fi
 
-# tput civis
+# Set times for `-t'.
+if $TIME_OK && [ "$MODE" == "-t" ]; then
+	TOTAL_SECONDS=$(( ($HOURS*60*60)+($MINUTES*60)+$SECONDS ))
+	DEST_TOTAL_SECONDS=$(( ($DEST_HOURS*60*60)+($DEST_MINUTES*60)+$DEST_SECONDS ))
+
+	if [ $TOTAL_SECONDS -le $DEST_TOTAL_SECONDS ]; then
+		let DEST_TOTAL_SECONDS-=$TOTAL_SECONDS
+	else
+		DEST_TOTAL_SECONDS=$(( ((24*60*60)-$TOTAL_SECONDS)+$DEST_TOTAL_SECONDS ))
+	fi
+
+	let DEST_HOURS=($DEST_TOTAL_SECONDS/60)/60
+	let DEST_MINUTES=($DEST_TOTAL_SECONDS/60)%60
+	let DEST_SECONDS=($DEST_TOTAL_SECONDS%60)%60
+fi
+
+if ! $IMMEDIATE; then
+	pause -r " Press any key to start timer ... "
+fi
+tput civis
 tput smcup
-pause -r # press any key to continue, then do carriage return.
+bin_bg
 print_info
 
 # For verify_time to verify for a {-c}ountdown, change the mode.
@@ -391,18 +345,27 @@ MODE="-c"
 TIME_OK=false
 verify_time
 
+tput cuf $TIMER_OFFSET
 while $TIME_OK; do
-	tput cuf $TIMER_OFFSET
-	printf "%02dh:%02dm:%02ds.\r" \
-		$DEST_HOURS $DEST_MINUTES $DEST_SECONDS
-
-	step_down
-	verify_time
-	sleep 1
+	tput setaf $COLOR
+	[ $COLOR -eq $COLOR_MAX ] && COLOR=$COLOR_MIN || let COLOR++
+	manage_time
 done
 
+tput sgr0
 tput cud 4
+tput cr
 play_sound
-pause -r " => Press any key to exit ... "
+
+if ! $IMMEDIATE; then
+	EXIT_PROMPT=" Press any key to exit ..."
+	PROMPT_OFFSET=$(( (($SPACER_NUM-${#EXIT_PROMPT})/2)+($SPACER_NUM%2) ))
+	tput cuu 4
+	tput cr
+	tput cuf $PROMPT_OFFSET
+	echo -n $EXIT_PROMPT
+
+	pause -r " "
+fi
 quit
 
